### ISSUE TITLE
Kebab case filenames

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/AmpersandTarski.github.io#11]
In December 2022, we had [a nasty problem](https://github.com/AmpersandTarski/AmpersandTarski.github.io/issues/10): A page in the documentation was accessible by navigating through the document structure (generated by Docusaurus), but it was not accessible as a raw URL.

On Dec 18th, @hanjoosten hypothesized that this has to do with the fact that Docusaurus transforms everything to lowercase identifiers. This requires that all file names in the `/docs` directories of the Ampersand repo, the RAP repo, and the Prototype repo must be in lowercase.

To avoid future novices from stumbling into this problem inadvertently, we need:
1. a line in the documentation instruction saying that filenames *must* be in lowercase.
2. a test during the deployment of the documentation that blocks publication if the documentation repositories contain a .md-file that contains characters other than lowercase, underscores, or hyphens, to enforce the policy and prevent the nasty problem from recurring.

**Comment by Michiel-s** [comment]
There is a setting for this to prevent broken links in https://github.com/AmpersandTarski/AmpersandTarski.github.io/blob/main/ampersand-docs/docusaurus.config.js

Currently `onBrokenLinks` and `onBrokenMarkdownLinks` are set to `warm` instead of build fail. This means that you can spot the broken link in the terminal when developing.

Because we are still in de proces of moving content from old to new docs, this setting is on warn to be able to build-run the application.

If that proces is more or less done we can change the setting to 'throw'. Read about it here: https://docusaurus.io/docs/api/docusaurus-config#onBrokenLinks

**Comment by hanjoosten** [comment]
There is no problem. I fixed it with commit https://github.com/AmpersandTarski/AmpersandTarski.github.io/commit/701491b913c7805f05d191b6b35446d31c857b0d.

So what do you want to say in the documentation? The best I can think of is that we need to remember that url's are case sensitive. Duhuh.
