### ISSUE TITLE
Project Documentation and landingpage

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/AmpersandTarski.github.io#12]
# Context
The [Ampersand](https://ampersandtarski.gitbook.io/master/) project aims to derive information systems from specifications, written in a language called Ampersand. Currently, Ampersand is documented in separate repositories on [Gitbook](https://www.gitbook.com/). The documentation is aimed at different types of stakeholders: people who are just interested, students who have to do a course, computer professionals who want to use Ampersand, scientists who are curious to see the underlying mechanisms, software engineers who want to change Ampersand, etcetera. The documentation is hand-written in Markdown.

The AmpersandTarski organization on Github contains several repositories. The two main ones contain the source code:
  * [Ampersand-repo](https://github.com/AmpersandTarski/Ampersand). This contains the source code for the ampersand compiler. The main purpose of this compiler is to read an Ampersand script and generate files that can be used by the prototype framework to embody the desired information system. 
  * [Prototype-repo](https://github.com/AmpersandTarski/Prototype). This contains the source code for the prototype framework.

Two separate repositories exist for the documentation:
  * [User documentation](https://ampersandtarski.gitbook.io/documentation/), which is currently being served using [GitBook](https://docs.gitbook.com/), and
  * [Developer documentation](https://ampersandtarski.gitbook.io/the-tools-we-use-for-ampersand/), which is also on GitBook.

# Challenge
1. The documentation of Ampersand is perpetually lagging behind because it resides in separate repositories, outside the code repository of Ampersand itself. We want the documentation to be in-sync with the current version of Ampersand and we want the updated documentation to be published automatically.
2. We want to be in control ourselves and ensure that all references to a url are reliable over time.

# Business value
 - a more reliable user experience because documentation is up to date with the release it documents.
 - documentation of earlier releases is accessible.
 - automation enables developers to combine coding with documenting in the same release, yielding more consistency.
 - integration of documentation in the CI/CD pipeline saves work for developers updating Ampersand.

# Scope

# Direction of Solution
A developer of Ampersand should be able to change the documentation and the code in the same branch. We think that if we would have a `docs` directory in the repositories Ampersand and prototype, we can tempt and persuade developers to write the documentation already during the implementation of a new feature. 
The idea is to use [GitHub actions](https://docs.github.com/en/actions) to create a CI/CD workflow that triggers a pull request into the main branch, and that would update the site where the documentation is served. For an attractive presentation of the documentation, we want to generate a static site using a tool like for instance [Jekyll](https://jekyllrb.com/) or [Docusaurus](https://docusaurus.io/docs). That site can then be served to the public by GitHub pages.
### Proposed steps
1. Assess the structure of the existing documentation and see if it is sufficiently compatible with Docusaurus or Jekyll (or whatever).
2. Refactor the CI/CD pipeline
3. Port the source code of the documentation (Markdown + files)
4. Validate

# MVP Criteria
  * CI/CD is in place, that will update a site where the documentation of the `docs` directories in the repositories [Ampersand] and [prototype] are being served. That CI/CD should trigger whenever a pull request is merged into the main branch in any of these two repositories.
  * The actual documentation from GitBook is moved into the Ampersand repo.

# Boundary Conditions
  * We want to stick to markdown for writing documentation
  * Since we have no budget, the Ampersand project sticks to free software solutions.

# Suggested solution
See [this comment](https://github.com/AmpersandTarski/AmpersandTarski.github.io/issues/12).

**Comment by Michiel-s** [comment]
![image](https://user-images.githubusercontent.com/7961582/182208712-8ddb8047-d721-498c-a9f7-13de8b26d0b1.jpeg)

**Comment by hanjoosten** [comment]
The idea of above image is as follows:

In the _new_ situation, we have a docs directory in both the [Ampersand repository](https://github.com/AmpersandTarski/Ampersand) (= compiler) and in the [Prototype repository](https://github.com/AmpersandTarski/prototype). 
When in either repositories anything is pushed to the main branch (by means of a pull request), we want to trigger a [Github action](https://github.com/features/actions) to build the documentation.
This task will get the docs folders of both repositories to build a single page website that can be made available via [Github pages](https://pages.github.com/).

**Comment by hanjoosten** [comment]
In the _old_ situation, we have our documentation in a [separate repository](https://github.com/AmpersandTarski/documentation). It is managed by means of [Gitbook](https://www.gitbook.com/). Gitbook automates the ci/cd whenever a commit is made to that repository, but it is hard to impossible to keep the documentation in sync with the releases of Ampersand and Prototype.

**Comment by hanjoosten** [comment]
# Suggested solution

To help the A-team find a realistic solution for this challenge, please see below some thoughts on what could be done.

To make this list as specific as possible, I will suggest some tooling. Be aware that these are just suggestions. It is well possible that the team brings in another tooling that is a better fit for the job. 

- [x] Create a new repository, [AmpersandTarski.github.io](https://github.com/AmpersandTarski/AmpersandTarski.github.io), at [AmpersandTarski](https://github.com/AmpersandTarski). This repo will contain the workflows needed to generate a single-page website for the documentation.
- [ ] Create a new development branch in the [Ampersand repo](https://github.com/AmpersandTarski/Ampersand) for the purpose of [this project](https://github.com/orgs/AmpersandTarski/projects/3). Consider that branch as the main branch for its lifespan. At the end of the project, it will be pulled into the real main branch.
- [ ] Use this development branch to create a `docs` directory in the Ampersand repo. To start with, let it contain a basic (hello world) page.
- [ ] Define a GitHub workflow inside the new repo. The goal of that workflow is to generate a single-page website from the contents of the docs directory in the development branch of Ampersand. The workflow should be triggered any time when there is a new commit/merge/pull request of the development branch of Ampersand. Use [github pages](https://docs.github.com/en/pages) to serve this single-page website. Use [Docusaurus](https://docusaurus.io/docs/) as a generator.
- [ ] Now do the same for the [prototype repo](https://github.com/AmpersandTarski/prototype). There too, create a development branch. Rename the `doc` directory to `docs`. Make the workflow also trigger on a commit of the development branch of the Prototype repo. Within the workflow, now not only copy the docs directory of the Ampersand repo, but also the docs directory of Prototype. In the one-pager, these directories should co-exist. Maybe scaffold pages are required to make this happen. If so, these could be created and stored inside the new repo.
- [ ] Replace the hello-world page in the Ampersand repo with all contents from the [documentation repo](https://github.com/AmpersandTarski/documentation). If all above is realized, that content should be readily served on the GitHub page.
- [ ] I assume that the Markdown dialect is a perfect match, but chances are that there are differences. Check the documentation thoroughly.
- [ ] Optionally, you might want to restructure all or some of the documentation. This might be beyond scope because it could require too much inside knowledge of Ampersand. 



## Pointers 
In order to make these things happen, here are some pointers for further reading:

* [Github workflows](https://docs.github.com/en/actions/using-workflows) is the way CI/CD tasks can be realized within GitHub.
* [Github pages](https://docs.github.com/en/pages) is the way a single-page website can be hosted at GitHub.
* [Here](https://github.com/LayZeeDK/github-pages-docusaurus/blob/main/.github/workflows/deploy-to-github-pages.yml) and [here](https://github.com/redkubes/docusaurus-deploy-action) you can find examples using Docusaurus to generate a GitHub pages site with a GitHub workflow. I expect that other examples can be found easily as well.
